services:
  db:
    image: postgres:16-alpine
    container_name: colaai-db
    environment:
      POSTGRES_DB: colaai
      POSTGRES_USER: colaai
      POSTGRES_PASSWORD: colaai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U colaai -d colaai"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: colaai-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/colaai
      SPRING_DATASOURCE_USERNAME: colaai
      SPRING_DATASOURCE_PASSWORD: colaai
      # (mais tarde) JWT_SECRET: "um-segredo-bem-grande-aqui"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: colaai-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
